[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "pkg-config",
  "libusb1",
  "gcc",
  "gnumake"
]

[phases.install]
cmds = [
  "npm config set python $(command -v python3)",
  "npm install --omit=dev"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

