[phases.setup]
nixPkgs = [
  "nodejs_20",
  "python3",
  "pkg-config",
  "libusb1",
  "systemd.dev",
  "gcc",
  "gnumake"
]

[phases.install]
cmds = [
  "export PYTHON=$(which python3)",
  "npm install --omit=dev --no-optional"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

